### ISSUE TITLE
Mailbox Validator Registration

### ISSUE THREAD

**Issue by FeelsBadMan1** [MailboxValidator/mailboxvalidator-phpbb#1]
Hello,
I tried to sign up for a account on the Website but then it gave me the Error "Free email address is not eligible for the free API."
Im not exaclty sure why this happend (used gmail & yahoo) but i dont like that. I wont spend Money on a E-Mail for become a free trail...

**Comment by MailboxValidator** [comment]
HiFeelsBadMan1, 

Yes, you can only sign up for a free MailboxValidator account using non-free email address.
